### ISSUE TITLE
2.0.0 Stable tag

### ISSUE THREAD

**Issue by scott1702** [tractorcow/silverstripe-proxy-db#7]
Currently we can't install silverstripe-auditor and silverstripe-debugbar together. The outstanding issue is pending a stable 2.0.0 https://github.com/silverstripe/silverstripe-auditor/pull/49 if you could please tag this stable 🙏

**Comment by lekoala** [comment]
:) yes! please, been running it for a while, and it's working fine

**Comment by jareddreyerss** [comment]
@tractorcow any chance this is on the radar to be done soon? :)

**Comment by tractorcow** [comment]
Sorry, thanks for @ me, I got the message now :)

**Comment by tractorcow** [comment]
https://github.com/tractorcow/silverstripe-proxy-db/releases/tag/2.0.0

**Comment by tractorcow** [comment]
cc @scott1702 @jareddreyerss tag up
